export default [
    "What’s something that inspired me lately?",
    "Based on my notes, what themes seem to matter most to me?",
    "Can you create a ‘motto’ or life philosophy based on my notes?",
    "What have been some of my recent “aha” moments?",
    "What do my notes say about my creative side?",
    "What are the unique perspectives I bring to my work or personal life?",
    "Is there a recurring mindset or attitude that’s holding me back?",
    "What should I be more careful about health-wise?",
    "Tell me a quote from a book that I enjoyed?",
    "Can you suggest something I’d likely enjoy doing today?",
    "Have I noted any patterns in my mood or energy levels?",
    "Are there specific activities or habits I’ve mentioned that improve my general well being?",
    "Can you tell me any goals I’ve set for myself?",
    "Who are the people I mention most frequently in my notes, and what’s the context?",
    "Are there any books, podcasts, or media I’ve repeatedly mentioned or enjoyed?",
    "Have I tracked any health trends or symptoms over the past year?",
    "What ideas have I jotted down?",
    "Have I met any new people lately?",
    "What stuff do I keep meaning to try but haven’t gotten around to?",
    "Do I have any travel plans in the coming week/month?",
    "Have I mentioned any bucket list items I would want to tick off this year?",
    "What tools or apps have I found helpful?",
]
