
auth.token=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

defaults.org=voicenotes-04
defaults.project=voicenotes-expo

defaults.url=https://sentry.io/
