export const RecordingStatus = {
  PROCESSING_AUDIO: 0,
  PROCESSING_FAILED: 1,
  AUDIO_PROCESSED: 2,
  UPLOADING_AUDIO: 3,
  AUDIO_UPLOADED: 4,
  UPLOADED_FAILED: 5,
  TRANSCRIPT_GENERATION_STARTED: 6,
  TRANSCRIPT_GENERATED: 7,
  GENERATE_TRANSCRIPT_FAILED: 8,
  RELATED_NOTES_FETCHED: 9,
  TITLE_GENERATED: 10,
  GENERATE_TITLE_FAILED: 11,
  FORMAT_TRANSCRIPT_STARTED: 12,
  TRANSCRIPT_FORMATTED: 13,
  FORMAT_TRANSCRIPT_FAILED: 14,
  PROCESS_COMPLETED:15,
  MEETING_SUMMARY_GENERATED:16
};

export const RecordingStatusString = Object.fromEntries(
  Object.entries(RecordingStatus).map(([key, value]) => [value, key])
);
