import React, {
    createContext,
    useState,
    useEffect,
    useContext,
    useCallback,
    useRef // Added useRef for AppState listener stability
} from 'react';
import {
    Platform,
    NativeModules,
    DeviceEventEmitter, // For Android events
    NativeEventEmitter, // Keep for potential future iOS events
    AppState, AppStateStatus, // To check for files when app comes to foreground (iOS)
} from 'react-native';

interface SharedItem {
    id: string; // Unique ID generated by native code
    type: 'file' | 'text' | 'url';
    mimeType: string; // Determined MIME type
    fileName?: string; // For type 'file'
    path?: string; // For type 'file' (should include file:// scheme from native)
    content?: string; // For type 'text' or 'url'
}

// --- Native Module Access ---
const { ShareReceiver } = NativeModules;
if (!ShareReceiver) {
    console.warn(
        "Native Module 'ShareReceiver' not found. Sharing features will not work. Did you rebuild the app after adding native code?"
    );
}

// --- Context Definition ---
const SharedFilesContext = createContext({
    sharedItems: [] as SharedItem[],
    error: null as string | null,
    isLoading: false, // Added loading state for checks
    clearDisplayedItems: () => {},
    clearNativeCache: async (): Promise<void> => {},
    checkIosItems: async (): Promise<void> => {},
});

// --- Provider Component ---
export const SharedFilesProvider = ({ children }: { children: React.ReactNode }) => {
    const [sharedItems, setSharedItems] = useState<SharedItem[]>([]);
    const [error, setError] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState<boolean>(false); // Loading state

    // Ref for AppState listener to avoid stale closures with checkForIosSharedItems
    const appState = useRef(AppState.currentState);

    // --- iOS: Check for items function (memoized) ---
    const checkForIosSharedItems = useCallback(async () => {
        if (Platform.OS !== 'ios' || !ShareReceiver?.checkForSharedItems) {
            return;
        }
        console.log('[Context] Checking for iOS shared items...');
        setIsLoading(true); // Set loading true
        setError(null); // Clear previous errors
        try {
            // Call the updated native method name
            const items: SharedItem[] | null | undefined = await ShareReceiver.checkForSharedItems();

            if (items && Array.isArray(items)) {
                if (items.length > 0) {
                    console.log(`[Context] Received ${items.length} new items from iOS:`, items);
                    // *** REPLACE state entirely with the new items ***
                    setSharedItems(items);
                } else {
                    console.log('[Context] iOS check returned empty array. Clearing display.');
                    // *** REPLACE state with empty array ***
                    setSharedItems([]);
                }
            } else {
                console.warn('[Context] iOS check returned non-array or null/undefined. Clearing display.', items);
                setSharedItems([]); // Clear display if response is invalid
            }
        } catch (e: any) {
            console.error('[Context] Error checking for iOS shared items:', e);
            setError(`iOS Check Error: ${e.message || 'Unknown error'}`);
            // setSharedItems([]); // Optionally clear items on error
        } finally {
            setIsLoading(false); // Set loading false
        }
    }, []); // Empty dependency array - function is stable

    // --- iOS: AppState listener ---
    useEffect(() => {
        if (Platform.OS !== 'ios') return;

        const handleAppStateChange = (nextAppState: AppStateStatus) => {
            if (
                appState.current.match(/inactive|background/) &&
                nextAppState === 'active'
            ) {
                console.log('[Context] App active! Checking iOS items.');
                checkForIosSharedItems(); // Call the check function
            }
            appState.current = nextAppState; // Update the ref
        };

        const subscription = AppState.addEventListener('change', handleAppStateChange);
        console.log('[Context] iOS AppState listener added.');

        return () => {
            subscription.remove();
            console.log('[Context] iOS AppState listener removed.');
        };
    }, [checkForIosSharedItems]); // Re-run if check function identity changes (it shouldn't with useCallback)

    // --- Android: Event listener ---
    useEffect(() => {
        if (Platform.OS !== 'android') return;

        console.log('[Context] Setting up Android share listener for "onShareReceived"...');
        const subscription = DeviceEventEmitter.addListener(
            'onShareReceived', // Event name emitted from MainActivity.kt
            (event: { items?: any[] }) => { // Expect payload like { items: [...] }
                setError(null); // Clear previous errors on new event
                if (event?.items && Array.isArray(event.items)) {
                    if (event.items.length > 0) {
                        console.log(`[Context] Received ${event.items.length} new items from Android:`, event.items);
                        // *** REPLACE state entirely with the new items from the event ***
                        setSharedItems(event.items);
                    } else {
                        console.log('[Context] Android event received empty items array. Clearing display.');
                        // *** REPLACE state with empty array if event has empty items ***
                        setSharedItems([]);
                    }
                } else {
                    console.warn('[Context] Received Android share event with missing or invalid "items" key:', event);
                    // setSharedItems([]); // Optionally clear state if event format is wrong
                }
            }
        );

        return () => {
            console.log('[Context] Removing Android share listener.');
            subscription.remove();
        };
    }, []); // Run only once on mount

    // --- Initial Check (iOS) ---
    useEffect(() => {
        // Run the check once when the provider mounts for the first time
        if (Platform.OS === 'ios') {
            checkForIosSharedItems();
        }
    }, [checkForIosSharedItems]); // Depend on the memoized check function

    // --- Context Helper Functions ---
    const clearDisplayedItems = useCallback(() => {
        setSharedItems([]);
        setError(null); // Also clear any error message
        console.log('[Context] Cleared displayed items list manually.');
    }, []);

    const clearNativeCache = useCallback(async () => {
        console.log('[Context] Attempting to clear native file cache...');
        setError(null);
        setIsLoading(true);
        try {
            if (ShareReceiver?.clearSharedFilesCache) {
                await ShareReceiver.clearSharedFilesCache();
                console.log('[Context] Native file cache cleared successfully.');
            } else {
                console.warn('[Context] clearSharedFilesCache method not available in native module.');
            }
        } catch(e: any) {
            console.error('[Context] Error clearing native file cache:', e);
            setError(`Clear Cache Error: ${e.message || 'Unknown error'}`);
        } finally {
            setIsLoading(false);
        }
    }, []);

    // Value provided by the context
    const value = {
        sharedItems,
        error,
        isLoading, // Provide loading state
        clearDisplayedItems,
        clearNativeCache,
        checkIosItems: checkForIosSharedItems // Expose manual check
    };

    return (
        <SharedFilesContext.Provider value={value}>
            {children}
        </SharedFilesContext.Provider>
    );
};

// --- Custom Hook for Consumption ---
export const useSharedItems = () => {
    const context = useContext(SharedFilesContext);
    if (context === undefined) {
        throw new Error('useSharedItems must be used within a SharedFilesProvider');
    }
    return context;
};
