// context/SharedFilesContext.js
import React, {
    createContext,
    useState,
    useEffect,
    useContext,
    useCallback,
    useRef, // Keep useRef for AppState stability
    ReactNode, // Import ReactNode for children prop typing
} from 'react';
import {
    Platform,
    NativeModules,
    DeviceEventEmitter, // For Android events
    NativeEventEmitter, // Keep for potential future iOS events or if bridging notifications
    AppState, // To check for files when app comes to foreground (iOS)
    AppStateStatus, // Type for AppState status
} from 'react-native';

// --- Type Definition (Optional but Recommended) ---
interface SharedItem {
    id: string; // Unique ID generated by native code
    type: 'file' | 'text' | 'url';
    mimeType: string; // Determined MIME type
    fileName?: string; // For type 'file'
    path?: string; // For type 'file' (should include file:// scheme from native)
    content?: string; // For type 'text' or 'url'
}

interface SharedFilesContextType {
    sharedItems: SharedItem[];
    error: string | null;
    isLoading: boolean; // To indicate if a check is in progress
    clearDisplayedItems: () => void;
    clearNativeCache: () => Promise<void>;
    checkIosItems: () => Promise<void>; // Expose manual check
    processSharedItem: (item: SharedItem) => SharedItem | null; // Process a shared item once
}

// --- Native Module Access ---
const {ShareReceiver} = NativeModules;
// Add a check to provide a warning if the module isn't linked
if (!ShareReceiver && (Platform.OS === 'ios' || Platform.OS === 'android')) {
    console.warn(
        "Native Module 'ShareReceiver' not found. Sharing features will not work. Did you rebuild the app after adding native code and run pod install?"
    );
}

// --- Context Definition ---
// Provide default values matching the ContextType interface
const defaultContextValue: SharedFilesContextType = {
    sharedItems: [],
    error: null,
    isLoading: false,
    clearDisplayedItems: () => {
    },
    clearNativeCache: async () => {
    },
    checkIosItems: async () => {
    },
    processSharedItem: (item: SharedItem) => item,
};
const SharedFilesContext = createContext<SharedFilesContextType>(defaultContextValue);

// --- Provider Component ---
interface SharedFilesProviderProps {
    children: ReactNode;
}

export const SharedFilesProvider = ({children}: SharedFilesProviderProps) => {
    const [sharedItems, setSharedItems] = useState<SharedItem[]>([]);
    const [error, setError] = useState<string | null>(null);
    // Loading state to prevent concurrent checks, especially on iOS
    const [isLoading, setIsLoading] = useState<boolean>(false);
    // Use ref for AppState listener stability
    const appState = useRef(AppState.currentState);
    // Track processed item IDs to prevent duplicate processing
    const processedItemIdRef = useRef<string | null>(null);

    // --- iOS: Check for items function (memoized) ---
    const checkForIosSharedItems = useCallback(async (triggerSource: string) => {
        console.log(`[Context] checkForIosSharedItems triggered by: ${triggerSource}. Current isLoading: ${isLoading}`); // Log trigger and isLoading state

        // *** Prevent concurrent runs using isLoading state ***
        if (isLoading) {
            console.log('[Context] checkForIosSharedItems: Check already in progress, skipping.');
            return;
        }

        if (Platform.OS !== 'ios' || !ShareReceiver?.checkForSharedItems) {
            return; // Silently return if not applicable
        }
        // Check if module exists before calling
        if (!NativeModules.ShareReceiver) {
            console.error("[Context] NativeModules.ShareReceiver is null or undefined!");
            setError("Native ShareReceiver module not linked.");
            return; // Cannot proceed
        }

        console.log('[Context] checkForIosSharedItems: Starting check...');
        setIsLoading(true); // Set loading true
        setError(null); // Clear previous errors
        try {
            console.log('[Context] checkForIosSharedItems: Calling NativeModules.ShareReceiver.checkForSharedItems...');
            // Assume native method returns SharedItem[] | null | undefined
            const items: SharedItem[] | null | undefined = await ShareReceiver.checkForSharedItems();
            console.log('[Context] checkForIosSharedItems: Native call returned:', JSON.stringify(items));

            // Update state based on result (REPLACE logic)
            if (items && Array.isArray(items)) {
                // Use functional update and log previous state for comparison
                setSharedItems(prevItems => {
                    const newItemsJson = JSON.stringify(items);
                    const prevItemsJson = JSON.stringify(prevItems);
                    // Only log update if items actually change to reduce noise
                    if (newItemsJson !== prevItemsJson) {
                        if (items.length > 0) {
                            console.log(`[Context] checkForIosSharedItems (${triggerSource}): Updating state with ${items.length} items.`);
                        } else {
                            console.log(`[Context] checkForIosSharedItems (${triggerSource}): Native returned empty array, clearing state.`);
                        }
                        return items; // Replace state
                    } else {
                        console.log(`[Context] checkForIosSharedItems (${triggerSource}): Native returned same items as current state, skipping state update.`);
                        return prevItems; // Return previous state if no change
                    }
                });
            } else {
                console.warn('[Context] checkForIosSharedItems: Received invalid data (null, undefined, or not array). Clearing state.');
                setSharedItems([]); // Clear state if response is invalid
            }
        } catch (e: any) {
            console.error('[Context] Error during checkForIosSharedItems native call:', e);
            setError(`iOS Check Error: ${e.message || 'Unknown error'}`);
        } finally {
            console.log('[Context] checkForIosSharedItems: Check finished.');
            setTimeout(() => setIsLoading(false), 0);
        }
    }, []);

    // --- iOS: AppState listener ---
    useEffect(() => {
        if (Platform.OS !== 'ios') return;

        const handleAppStateChange = (nextAppState: AppStateStatus) => {
            const currentAppState = appState.current; // Capture state at time of event
            if (
                currentAppState.match(/inactive|background/) &&
                nextAppState === 'active'
            ) {
                // Check isLoading state directly before calling
                // Use a local variable to capture isLoading state at this exact moment
                const currentlyLoading = isLoading;
                console.log(`[Context] App became active! Current isLoading: ${currentlyLoading}. Triggering check...`);
                if (!currentlyLoading) {
                    checkForIosSharedItems('AppState active'); // Pass trigger source
                } else {
                    console.log('[Context] App became active but check already in progress, skipping trigger.');
                }
            }
            appState.current = nextAppState; // Update the ref
        };

        const subscription = AppState.addEventListener('change', handleAppStateChange);
        console.log('[Context] iOS AppState listener added.');

        console.log('[Context] Initial mount: Scheduling check...');
        const initialCheckTimeout = setTimeout(() => {
            const currentlyLoading = isLoading; // Check isLoading right before calling
            console.log(`[Context] Initial mount check executing. Current isLoading: ${currentlyLoading}`);
            if (!currentlyLoading) {
                checkForIosSharedItems('Initial mount'); // Pass trigger source
            } else {
                console.log('[Context] Initial mount check skipped, already loading.');
            }
        }, 100); // Short delay to allow initial render potentially setting isLoading


        return () => {
            subscription.remove();
            clearTimeout(initialCheckTimeout);
            console.log('[Context] iOS AppState listener removed.');
        };
    }, [checkForIosSharedItems]); // Depend on check function and isLoading


    // --- Android: Event listener ---
    useEffect(() => {
        if (Platform.OS !== 'android') return;

        console.log('[Context] Setting up Android share listener for "onShareReceived"...');
        const subscription = DeviceEventEmitter.addListener(
            'onShareReceived', // Event name emitted from MainActivity.kt
            (event: { items?: SharedItem[] }) => { // Expect payload like { items: [...] }
                console.log('[Context] Android onShareReceived event:', JSON.stringify(event));
                setError(null); // Clear previous errors on new event
                if (event?.items && Array.isArray(event.items)) {
                    // REPLACE state with items from this specific event
                    setSharedItems(event.items);
                    if (event.items.length > 0) {
                        console.log(`[Context] Android listener updated state with ${event.items.length} items.`);
                    } else {
                        console.log(`[Context] Android listener received empty items array.`);
                    }
                } else {
                    console.warn('[Context] Received Android share event with missing or invalid "items" key:', event);
                    setSharedItems([]); // Clear state if event format is wrong
                }
            }
        );

        return () => {
            console.log('[Context] Removing Android share listener.');
            subscription.remove();
        };
    }, []); // Run only once on mount


    // --- Context Helper Functions ---
    const clearDisplayedItems = useCallback(() => {
        setSharedItems([]);
        setError(null);
        console.log('[Context] Cleared displayed items list manually.');
    }, []);

    // Process a shared item once, preventing duplicate processing
    const processSharedItem = useCallback((item: SharedItem): SharedItem | null => {
        if (!item?.id) {
            console.warn("[Context] processSharedItem: Received shared item without an ID.");
            throw new Error("Shared item must have a valid ID.");
        }

        if (item.id === processedItemIdRef.current) {
            console.log(`[Context] processSharedItem: Shared item ID ${item.id} already processed.`);
            // Return null as requested in the issue description
            return null;
        }

        // Mark this item as processed
        console.log(`[Context] processSharedItem: Processing new shared item ID: ${item.id}`);
        processedItemIdRef.current = item.id;

        return item; // Return the item for further processing
    }, []);

    const clearNativeCache = useCallback(async () => {
        // Check if module and function exist before calling
        if (!ShareReceiver?.clearSharedFilesCache) {
            console.warn('[Context] clearNativeCache function not available in native module.');
            setError('Native cache clearing function not available.');
            return;
        }
        console.log('[Context] Attempting to clear native file cache...');
        setError(null);
        setIsLoading(true); // Use loading state for cache clearing too? Optional.
        try {
            await ShareReceiver.clearSharedFilesCache();
            console.log('[Context] Native file cache cleared successfully.');
        } catch (e: any) {
            console.error('[Context] Error clearing native file cache:', e);
            setError(`Clear Cache Error: ${e.message || 'Unknown error'}`);
        } finally {
            setIsLoading(false); // Reset loading state
        }
    }, []); // No dependencies needed if ShareReceiver is stable

    // Value provided by the context
    const value: SharedFilesContextType = {
        sharedItems,
        error,
        isLoading,
        clearDisplayedItems,
        clearNativeCache,
        checkIosItems: () => checkForIosSharedItems('manual'),
        processSharedItem,
    };

    return (
        <SharedFilesContext.Provider value={value}>
            {children}
        </SharedFilesContext.Provider>
    );
};

// --- Custom Hook for Consumption ---
export const useSharedItems = (): SharedFilesContextType => {
    const context = useContext(SharedFilesContext);
    if (context === undefined) {
        // This error means you are trying to use the context outside of its provider
        throw new Error('useSharedItems must be used within a SharedFilesProvider');
    }
    return context;
};
